package com.mur.model.role;

public class RoleUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user_rel.USER_ID
     *
     * @mbggenerated Mon Jan 09 13:50:22 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user_rel.ROLE_ID
     *
     * @mbggenerated Mon Jan 09 13:50:22 CST 2017
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user_rel.USER_ID
     *
     * @return the value of role_user_rel.USER_ID
     *
     * @mbggenerated Mon Jan 09 13:50:22 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user_rel.USER_ID
     *
     * @param userId the value for role_user_rel.USER_ID
     *
     * @mbggenerated Mon Jan 09 13:50:22 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user_rel.ROLE_ID
     *
     * @return the value of role_user_rel.ROLE_ID
     *
     * @mbggenerated Mon Jan 09 13:50:22 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user_rel.ROLE_ID
     *
     * @param roleId the value for role_user_rel.ROLE_ID
     *
     * @mbggenerated Mon Jan 09 13:50:22 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
}