package com.mur.mapper.menuItem;

import java.util.List;

import com.mur.model.menuItem.MenuItem;
import com.mur.model.menuItem.MenuItemQuery;

public interface MenuItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_item
     *
     * @mbggenerated Mon Jan 09 16:05:47 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_item
     *
     * @mbggenerated Mon Jan 09 16:05:47 CST 2017
     */
    int insert(MenuItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_item
     *
     * @mbggenerated Mon Jan 09 16:05:47 CST 2017
     */
    int insertSelective(MenuItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_item
     *
     * @mbggenerated Mon Jan 09 16:05:47 CST 2017
     */
    MenuItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_item
     *
     * @mbggenerated Mon Jan 09 16:05:47 CST 2017
     */
    int updateByPrimaryKeySelective(MenuItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_item
     *
     * @mbggenerated Mon Jan 09 16:05:47 CST 2017
     */
    int updateByPrimaryKey(MenuItem record);
    
    int deleteAll();
    
    int insertBatch(List<MenuItem> menuItems);
    
    List<MenuItem> findMenuItems(MenuItemQuery menuItemQuery);
}