package com.mur.model.permission;

import com.mur.model.Entity;

public class Permission  extends Entity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.ID
     *
     * @mbggenerated Mon Jan 09 16:53:32 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.ROLE_ID
     *
     * @mbggenerated Mon Jan 09 16:53:32 CST 2017
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.MENU_ITEM_ID
     *
     * @mbggenerated Mon Jan 09 16:53:32 CST 2017
     */
    private String menuItemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.ID
     *
     * @return the value of permissions.ID
     *
     * @mbggenerated Mon Jan 09 16:53:32 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.ID
     *
     * @param id the value for permissions.ID
     *
     * @mbggenerated Mon Jan 09 16:53:32 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.ROLE_ID
     *
     * @return the value of permissions.ROLE_ID
     *
     * @mbggenerated Mon Jan 09 16:53:32 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.ROLE_ID
     *
     * @param roleId the value for permissions.ROLE_ID
     *
     * @mbggenerated Mon Jan 09 16:53:32 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.MENU_ITEM_ID
     *
     * @return the value of permissions.MENU_ITEM_ID
     *
     * @mbggenerated Mon Jan 09 16:53:32 CST 2017
     */
    public String getMenuItemId() {
        return menuItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.MENU_ITEM_ID
     *
     * @param menuItemId the value for permissions.MENU_ITEM_ID
     *
     * @mbggenerated Mon Jan 09 16:53:32 CST 2017
     */
    public void setMenuItemId(String menuItemId) {
        this.menuItemId = menuItemId;
    }
}