package com.mur.model.user;

import com.mur.enumrate.BaseStatus;
import com.mur.model.Entity;

/**
 * 用户
 * @author MuR
 *
 */
public class User  extends Entity{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.ID
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.CODE
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.NAME
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.PASSWORD
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.STATUS
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.ID
	 * @return  the value of users.ID
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.ID
	 * @param id  the value for users.ID
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.CODE
	 * @return  the value of users.CODE
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.CODE
	 * @param code  the value for users.CODE
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.NAME
	 * @return  the value of users.NAME
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.NAME
	 * @param name  the value for users.NAME
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.PASSWORD
	 * @return  the value of users.PASSWORD
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.PASSWORD
	 * @param password  the value for users.PASSWORD
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.STATUS
	 * @return  the value of users.STATUS
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.STATUS
	 * @param status  the value for users.STATUS
	 * @mbggenerated  Mon Jan 09 13:21:18 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}