package com.mur.mapper.role;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mur.model.role.RoleUser;
import com.mur.model.user.User;

public interface RoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user_rel
     *
     * @mbggenerated Mon Jan 09 13:50:22 CST 2017
     */
    int insert(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_user_rel
     *
     * @mbggenerated Mon Jan 09 13:50:22 CST 2017
     */
    int insertSelective(RoleUser record);
    
    
    int insertBatchUser(@Param("roleId") String roleId, @Param("users") List<User> user);
    
    int removeUser(@Param("roleId") String roleId, @Param("users") List<User> users);
}