package com.mur.mapper.role;

import java.util.List;

import com.mur.model.role.Role;
import com.mur.model.role.RoleQuery;
import com.mur.model.role.RoleVo;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Mon Jan 09 12:26:31 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Mon Jan 09 12:26:31 CST 2017
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Mon Jan 09 12:26:31 CST 2017
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Mon Jan 09 12:26:31 CST 2017
     */
    Role selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Mon Jan 09 12:26:31 CST 2017
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles
     *
     * @mbggenerated Mon Jan 09 12:26:31 CST 2017
     */
    int updateByPrimaryKey(Role record);
    
    List<RoleVo> findRoles(RoleQuery roleQuery);
}