package com.mur.model.enumrate;

import com.mur.model.Entity;

public class Enumrate extends Entity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enumrate.ID
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enumrate.ENUM_TYPE
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    private String enumType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enumrate.ENUM_VAL
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    private String enumVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enumrate.DISPLAY_NAME
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enumrate.REMARK
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enumrate.ID
     *
     * @return the value of enumrate.ID
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enumrate.ID
     *
     * @param id the value for enumrate.ID
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enumrate.ENUM_TYPE
     *
     * @return the value of enumrate.ENUM_TYPE
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    public String getEnumType() {
        return enumType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enumrate.ENUM_TYPE
     *
     * @param enumType the value for enumrate.ENUM_TYPE
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    public void setEnumType(String enumType) {
        this.enumType = enumType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enumrate.ENUM_VAL
     *
     * @return the value of enumrate.ENUM_VAL
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    public String getEnumVal() {
        return enumVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enumrate.ENUM_VAL
     *
     * @param enumVal the value for enumrate.ENUM_VAL
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    public void setEnumVal(String enumVal) {
        this.enumVal = enumVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enumrate.DISPLAY_NAME
     *
     * @return the value of enumrate.DISPLAY_NAME
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enumrate.DISPLAY_NAME
     *
     * @param displayName the value for enumrate.DISPLAY_NAME
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enumrate.REMARK
     *
     * @return the value of enumrate.REMARK
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enumrate.REMARK
     *
     * @param remark the value for enumrate.REMARK
     *
     * @mbggenerated Thu Jan 12 10:46:51 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}